version: '3.7'

services:
  db:
    container_name: tas-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: TAS
    ports:
      - "33306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d:ro
  app:
    container_name: tas-app
    image: app
    depends_on:
      - db
    restart: always
    env_file: ./.env
    volumes:
      - ./:/Users/javierteo/Documents/Projects/interview-package-ts-pg
      - ignore:/Users/javierteo/Documents/Projects/interview-package-ts-pg
volumes:
  ignore:
